### ISSUE TITLE
Apply asp.net identity

### ISSUE THREAD

**Issue by mahmoudrezenaseri** [mahmoudrezenaseri/anbardari#6]

**Comment by vlkn78** [comment]
![addnewscaffolded](https://github.com/mahmoudrezenaseri/anbardari/assets/143534318/bcbafd4c-5841-47d9-99b1-b85011b4bd50)


hi everyone,

I want to add Identity scaffolded item to my project.. But I cannot add it, because there is no Identity selection as shown at the photo attached.  How can I add it ? thank you..
